# Site settings
title: Pavan Sudhir Nallam
name: Pavan Sudhir Nallam 
resume_contact_email: "sudhir.nitw@gmail.com"

# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  
#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/sudhirnallam
 - title: LinkedIn
   url: http://www.linkedin.com/in/sudhir-nallam
#Any buzzword skills you want to include
skills:
 - Deep Learning
 - Machine Learning
 - Natural language processing
 - Python
 - Java
 - Pytorch
 - AWS
 - Elasticsearch
 - DevOps
 - RESTful Architecture
 - NoSQL databases

#Work experience is required
roles:
 - title: Data Scientist
   start: March, 2019
   end: Ongoing
   employer: Roku, Las Gatos, CA
   description: Working in Roku Voice NLU team. Exploring the data corpus using statistical and ML models to create actionable insights. Evaluating the models by defining KPI’s and conducting AB tests.
 - title: Data Scientist
   start: Sept, 2014
   end: Feb, 2019
   employer: IBM, T.J. Watson Research Center, NY
   description: Developed a predictive analytics tool to help the IBM M&A team to improve the procurement of new acquisitions. Worked on analyzing the public response on IBM sponsored events by doing sentimental analysis on twitter and blogs data. Designed and developed MAPro (Performance & Risk Optimizer), a web application with integrated cognos reports.
 - title: Software Engineer
   start: March, 2010
   end: Sept, 2014
   employer: IBM, T.J. Watson Research Center, NY
   description: Work closely with client teams to identify requirements, estimate projects, and implement prototypes and solutions in an agile, iterative fashion. Analytics (Data Mining) model developed in SPSS is integrated into the system through Python and Clementine Scripting. Designed and developed MAPro (Performance Risk Optimizer), a web application with integrated cognos reports. Developed low latency application through multi-threading and in-memory cache.
 - title: Software Engineer
   start: July, 2009
   end: March, 2010
   employer: Navy Federal Credit Union, Pittsburgh
   description: Migrated lotus notes based Reversal application to web based J2EE application in websphere. Connected to mainframe programs (wrapped by Host Bridge) through web service clients using restful webservices.
 - title: Software Engineer
   start: January, 2008
   end: July, 2009
   employer: FedEx Ground, Pittsburgh
   description: Contributed in increasing the project performance (4 million requests/day) by tuning the JDBC calls, monitoring the server using JProfiler, altering the service programs (AS/400 programs). Developed service layer programs and parsers which have optimized time complexity.
 - title: Software Engineer
   start: May, 2005
   end: July, 2006
   employer: Robert Bosch, India
   description: Implemented java based production configuration tool, to decrease the production downtime. Gained substantial knowledge about the concepts, design advantages, traps and pitfalls of successful object oriented design and programming.

#Education is required
education:
 - level: Master of Science
   date: 2015–2017
   subject: Data Science
   grade: 3.51/4.0
   school: New York University, New York
 - level: Master of Science
   date: 2006–2008
   subject: Mechanical & Aerospace Engineer
   grade: 3.27/4.0
   school: Illinois Institute of Technology, Chicago
 - level: Bachelor of Technology
   date: 2001–2005
   subject: Mechanical Engineer
   grade: 75.13/100
   school: National Institute of Technology, Warangal, India  


#List of interesting Github repo/projects to include - optional
github:
 - sudhirNallam/Unsupervised-training-using-SWWAE
 - sudhirNallam/Analysis-NYC-Taxi-data
 - sudhirNallam/Generative-Models-Limitations
 - sudhirNallam/predictingRefugeeAsylum
 - sudhirNallam/seq2seqModel
 - sudhirNallam/Energy-Disaggregation-Product-PoC-kaggle-competition
 
#Mobile apps section is optional
apps:
 - year: 2012
   company: IBM T.J. Watson Research center
   description: Outstanding Technical Achievement Award
 - year: 2014
   company: Coursera
   description: Machine Learning course by Andrew Ng

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: 
 - skill: Languages
   options: Python, R, Lua, C++, PL/SQL, Octave, Java
 - skill: Python Packages
   options: pandas, scikit-Learn, numpy, scipy, matplotlib, pymongo, Numba, Cython
 - skill: Tools & Technologies
   options: Torch, Tensorflow, Hadoop(ecosystem), Spark, SPSS, Elasticsearch, AWS, Airflow, Spring, Struts, Hibernate
 - skill: Databases
   options: Mongo DB, DB2, Cognos TM1
 - skill: Web Technologies
   options: HTML, CSS, AJAX, Restful services, XML, JSON, Javascript
 - skill: Visulization
   options: D3, Cognos BI
 - skill: OS
   options: Linux- RHEL, Ubuntu; Windows  
